### ISSUE TITLE
ERROR 52100

### ISSUE THREAD

**Issue by utente89** [barronwaffles/dwc_network_server_emulator#133]
Sorry guys I'm a newbie and I need some help. I have problems to connect to the server. This morning I could connect regularly, but now error 52100 appears! what can causes it? I really can't understand what's wrong with my conncection. 
Thank you.

**Comment by utente89** [comment]
I'm using Pokemon Heart Gold.

**Comment by RicoSantos** [comment]
The server usually goes offline for maintenance, this may be the reason you couldn't connect.

**Comment by utente89** [comment]
Thank you Rico. May the server shut down for two consecutive days ? 'Cause I'm trying right now and I still have this problem...Maybe someone banned me! It's such a pity, I was so enthusiastic about this new server. Anyways, this server is really a great project, hope it will replace all the nintendo services!

**Comment by ghost** [comment]
we need more than one server if we had another one  to use as a substitute for when the one we have goes down  for maintenance  these problems would less likely occur, I know it may be hard or even impossible to do, and I like at least having one server for old Wi-Fi, but hopefully we can try to get a few more servers to help when the one we have goes down for maintenance

**Comment by kyle95wm** [comment]
I can probably help there. I used to run a server but it was hardly popular so I shut it down. The reason I shut it down primarily was so that I could use my Pi for other things but I'm getting another Pi in a week or so maybe then I can use my current one for the server and my new one for anything else

**Comment by ghost** [comment]
thatd be great we need as many servers as possible

**Comment by kyle95wm** [comment]
Just a little update I checked my Amazon order and the Pi cases got delivered today now I'm just waiting for the Pi 2 which will come on Thursday this week.

I'll create a new wiki page of the list of servers using ALTWFC's code, their addresses, their status (they obviously need to be updated by the owner of the status) and if theres any rules because my server obviously has a sort of ban system (but not the best) so obviously no FTW hacking or code abuse

**Comment by ghost** [comment]
I created a lot of my pokemon through a program called pokegen  will your server ban the use of them I hope not because ev training and iv breeding is bullshit and takes a long time to do

**Comment by kyle95wm** [comment]
No, most of the bans will come from players on Mario Kart Wii since that game is my primary game. What ever games are supported by this server are sure to work with mine since the source is practically the same.

also I created the page - have a look

https://github.com/polaris-/dwc_network_server_emulator/wiki/List-of-Servers

**Comment by ghost** [comment]
I still need to get that game I saw some copies at Walmart for decent prices and don't worry about most hacking most wii hacking is done to just get the homebrew channel installed to connect to Wi-Fi now as for using an action replay im not even sure if one of those exists for the wii or not

**Comment by mm201** [comment]
@pkmntrainerryan Pokémon hax checks are handled by my server. Nothing is blocked yet but it's going to be in a couple months. Make sure your Pokémon have valid movesets, abilities, and legal EVs and they'll pass.

https://github.com/mm201/pkmnFoundations/issues/3

**Comment by ghost** [comment]
I didn't gen them to have moves or abilities  they cant get  nor illegal evs  I just gened them to  make getting competitive pokemon easier

**Comment by mm201** [comment]
Should be fine then.

**Comment by ghost** [comment]
ok, we also need a way to find battles brawls and mk races I tried finding battles on here once and I was told this is not the place to  ask  so we need a place where we can request battles/brawls/mk races using the server

**Comment by ghost** [comment]
i think a xat chat or Skype chat will do it

**Comment by mm201** [comment]
There's an official IRC chat, `#altwfc` on [irc.rizon.net](irc://irc.rizon.net). Unfortunately, not many players bother to check there. I guess we could add a web interface for it.

**Comment by Asvel2102** [comment]
dont know if this its the right place to ask this but, what about use action replay to have pokemons impossible to get? example: spiritomb from Diamond/Pearl/Platina, to get him normal it needs to speak with 32 players "local" in underground but it pratically impossible to find someone local today :s

**Comment by mm201** [comment]
In short, you'll probably be fine. Please use [the correct place](https://github.com/mm201/pkmnFoundations/issues/3) for further discussion.
