### ISSUE TITLE
 Address already in use (dnsmasq)

### ISSUE THREAD

**Issue by DevEkode** [barronwaffles/dwc_network_server_emulator#134]
Hi everyone

I try to install "dwc_network_server_emulator" on a vps hosted by OVH, no problem until I get a error from dnsmasq :

"dnsmasq: failed to create listening socket for 151.**.**_._**: Address already in use"

I looked for a solution for hours and I'll start getting tired.
Thank you in advance for your answers

NB: Sorry if my english is approximate, I'm french :D

**Comment by kyle95wm** [comment]
Did you happen to use my install script? My script was meant to be used by installations that use apt as their package managers. It went through several commits early this morning. If you haven't already check out the wiki for a page detailing the install.

**Comment by DevEkode** [comment]
I use the new install script and again I get the same error

NB: My vps os is Ubuntu 14.10 64bits

**Comment by kyle95wm** [comment]
Hmm. I would suggest starting the vps from scratch and trying the script on that. I've tested it on a 14.04 VM and it works fine. Also tested on Raspbian

**Comment by DevEkode** [comment]
I have already tried several times to start from scratch but nothing to do and that's why I'm here

**Comment by kyle95wm** [comment]
I honestly don't know then. It SHOULD have worked that's for sure. Did you use the script as soon as you brought up your vps or were you trying it manually? I think it's best if the devs come here to help you with your problem. I've encountered one other person who couldn't get dnsmasq to start and that's because he was running some weird Ubuntu thing. I could never help him fix it in the end. All I know is my script works for me and many others. I'm baffled why it's not working for you.

**Comment by DevEkode** [comment]
I think it comes from my host, but I don't know exactly where. Also I'll try to change my vps OS (debian, or other) and see if this solve the problem.

**Comment by DevEkode** [comment]
nothing to do always the same problem
