### ISSUE TITLE
Manually adding a PID?

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#172]
Hi,
As I work on both Wiimmfi and AltWFC (don't have a go at me, I just do) on my DS, I can see a PID yet it obviously DCs (6000)
Is there some way to manually insert the PID so I don't have to redo my fc every time? I'm talking via MySQL - I run my own server in-home.

**Comment by kyle95wm** [comment]
I know this had nothing to do with the answer but did you use my script to run your server?

Now as for manually adding PID's I don't think it's possible since random data is generated, and access to both Wiimmfi's database and yours are needed to get things like the password and GSBRCD and stuff like that.

**Comment by AdmiralCurtiss** [comment]
I haven't tried but I think you can probably just manually update the user table and set it that way.

**Comment by kyle95wm** [comment]
but how would he get the password and stuff for the various profiles?

**Comment by ghost** [comment]
I used the setup script and selected Polaris, yes. And I could always make the fc on altwfc and ask leseratte to stick it on wiimmfi .

----- Reply message -----

**Comment by ghost** [comment]
I can close this, thanks everyone
