### ISSUE TITLE
[Request] Please make instruction for set up AltWFC on windows.

### ISSUE THREAD

**Issue by the4anoni** [barronwaffles/dwc_network_server_emulator#188]
The request is in the topic.

**Comment by kyle95wm** [comment]
I too would be interested. Perhaps I can write a batch script once I know how it's all done

**Comment by the4anoni** [comment]
I also can help.
I installed on my notebook virtualbox + windows server 2012 r2 standard , so I can test scripts.

**Comment by sepalani** [comment]
I personally use Visual Studio 2015 with Python Tools.

For Windows you have to install the following python dependencies. If you don't have easy_install/pip, install them because there are very useful! Open a cmd console and do:

```
pip install twisted
easy_install zope.interface
pip install pypiwin32
```

Then you're done. The only thing you need to do from there is to forward requests properly using a DNS server for example.

AFAIK, I've edited the nas_server.py file to use the port 80 and my Windows' hosts file to forward every request to 127.0.0.1 because I'm using local servers. BTW, I'm testing altwfc servers with emulators.

**Comment by the4anoni** [comment]
Ok, but I don't have Vs 2015 , because I don't want install unnecesary add-ons.
What is minimal installation for dwc_server_emulator ( only python tools ???) ?
Ps. Can I install community version ???

**Comment by sepalani** [comment]
Short answer: python (cf. previous post).

Python Tools is just a VS extension that allows me to develop in python through Visual Studio. It doesn't install python, so the only thing you need to do is install python (I'm using python2.7).

You can access to python via a cmd/shell or IIRC by clicking twice on python script that doesn't require parameters when python is installed. As I said before, you need to install the dependencies with pip/easy_install via a cmd/shell or find corresponding executables to install those python modules on the Internet.

I highly encourage you to learn how to use a shell/cmd and python if you don't understand the paragraph above.

**Comment by the4anoni** [comment]
master_server.py runned sucessfully ,but I can't enter to admin page :(

**Comment by kyle95wm** [comment]
One successful connection must be made first before any of the other servers are accessible.

**Comment by the4anoni** [comment]
Ok, thanks but i can't test because my Dsi has broken and i must buy a new 3ds in next year :(

**Comment by polaris-** [comment]
Going to close this since the question was already answered and the person who opened the ticket was successful in running it already.
