### ISSUE TITLE
error 84020

### ISSUE THREAD

**Issue by AriaRigga** [barronwaffles/dwc_network_server_emulator#202]
Sir. When im trying to connect in random matchups, im always getting error 84020. Communication error. Im playing pokemon BW/BW2. Pls help me.

**Comment by mm201** [comment]
Sounds like https://github.com/polaris-/dwc_network_server_emulator/issues/162

The game can't find any players, so it eventually gives up with 84020, which just means it couldn't find anyone. (Even though they're actually there--the server just isn't pairing you like it should.)

**Comment by diegofontenelle** [comment]
Is there a fix for it already ? Tried it today and got the same error code while trying to connect for trading on HeartGold. I'm trying it on BeanJrFi since I got connection error when trying to connect to the ALTWFC, when I ping it I receive no response. 

Btw, I was using 2 emulators on different wired PCs.The roms were patched with WfcPatcher.
