### ISSUE TITLE
Error 84030

### ISSUE THREAD

**Issue by JustonB** [barronwaffles/dwc_network_server_emulator#204]
Hello, sorry for bothering you but I'm a bit stuck right now, so I thought I might as well ask away:
I've been trying to get two or more Desmume emulators, both active on a single computer, to play with one another, without any success. I managed to have both connected to the wifi at once, but wether it is through friend codes or free mode, when trying to get them to play together, the best I got was an error 84030, when the game didn't crash outright for one of the two.

So, is it even possible in the first place? If so, what might I be doing wrong?
Oh and the game I'm trying this on is Phantasy Star Zero, if that makes any difference.
Thanks in advance, have a nice day.

**Comment by sepalani** [comment]
I had the same issue with Dolphin Emulator in all Wii games I have but without raising any error codes. Concerning my case, I'm sure it's because Dolphin instances use the same NAND. Obviously, the same console even if connected multiple times can't find itself as opponent to play with in online mode. At least for few games I have.

On one hand, my PR https://github.com/polaris-/dwc_network_server_emulator/pull/197 should fix those instances crashes but on the other hand it will kick the same connected instances but one of them (the legit one).

You should try it with an emulator and a console or two emulators without the same console properties, it should fix your issue.
