### ISSUE TITLE
n00b question !

### ISSUE THREAD

**Issue by the4anoni** [barronwaffles/dwc_network_server_emulator#218]
Hello !
I want to know what PHP5 version i must install ( 5.0 from 2004 / 5.6 ).
Please reply !

**Comment by sepalani** [comment]
I didn't have one, Apache neither. But that's because I use the alternative config file which doesn't support GamestatsHTTP. Otherwise, I don't really know, I didn't see any PHP file in here. According to this PR https://github.com/polaris-/dwc_network_server_emulator/pull/6 I guess you may not need it.

Can someone confirm?

**Comment by the4anoni** [comment]
Thx for info but i also want know how to redirect nintendo dsi to my server ( server runned on windows ) :) and how i can kill python master_server (can't enter kill/exit or any command) so i just close it as normal windows program. Is this method is ok ? ( are matchrankings save without any command ? )
