### ISSUE TITLE
All DLC files in repo?

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#237]
Hi all,
Can a main dev with access to the repo add in all the DLC?

**Comment by ghost** [comment]
@polaris- Do you have access to them?
It'd be better for other servers like BeanJrFi

**Comment by windwakr** [comment]
Here's everything I have:
http://b.1339.cf/lgxefcl.7z
Grabbed most of it from the official servers before they shut down, but I grabbed a couple of things(like Band Brothers) from this server shortly afterwards.
I think it should have most of the stuff listed on this page:
https://github.com/polaris-/dwc_network_server_emulator/wiki/Nintendo-DS-Download-Content

Would be nice to see a release of everything Nagato managed to grab(like the user created WW:DIY stuff), but I doubt that'll ever happen.

**Comment by ghost** [comment]
Thank you! :D

**Comment by AdmiralCurtiss** [comment]
There was a question of the legality of putting official DLC into the repository, even if it was free, which is why we decided against it. The Pokemon stuff currently in it was reverse-engineered from save files that had the content downloaded, as the distribution of them was no longer available when we started capturing data, which is why we did put that in at least.

**Comment by PokeAcer549** [comment]
I see. Would one consider placing a link to them instead?


Sent from Outlook Mobile






On Mon, Jan 18, 2016 at 1:47 AM -0800, "AdmiralCurtiss" <notifications@github.com> wrote:





There was a question of the legality of putting official DLC into the repository, which is why we decided against it. The Pokemon stuff currently in it was reverse-engineered from save files that had the content downloaded, as the distribution of them was no longer available when we started capturing data, which is why we did put that in at least.

---

**Comment by ghost** [comment]
A friend is working on a big list of ID4s that AltWFC has DLS1 files for - I have a downloader which reads the file and downloads the files from AltWFC (If you've been seeing a ton of requests in your logs from 185.82.21.64 or 185.82.22.28 it's me :P), then stores them for me. Once the list is done I may release it, though I didn't make it, I was given it by einstein95
