### ISSUE TITLE
Donations to tech devs/server hosts

### ISSUE THREAD

**Issue by Saiyaken-PHOENIX** [barronwaffles/dwc_network_server_emulator#260]
Please implement a way to donate to the developers of the AltWFC Network server and server hosts.  I have seen this project languishing recently and I really want this to grow into something big.  My goal is to see the majority of supported games have at least 4-8 people connecting ingame, everyday.  I also want to see a forum where people can share information like friend codes and linkup times.  If there was a way I could make these things happen myself, I'd definitely do it, but time constraints and lack of knowledge of the systems prevent me from doing so.

**Comment by gokucopkake** [comment]
i agree your idea if you need help iam here

**Comment by Saiyaken-PHOENIX** [comment]
Yes, I'd love for the AltWFC community to grow; updates and development may
just be the trick to get it to reach a critical mass. I enjoy using the
AltWFC service, and would love to see someone form a viable community for
it to flourish.

**Comment by kyle95wm** [comment]
Im actually paying $5/month to host ~~this~~ _my own_ server, on top of a forum for my community and whatnot. Donations would be much appreciated: http://paypal.me/kyle95wm

**Comment by polaris-** [comment]
@kyle95wm While I appreciate your contributions to the project, your comment seems to imply that you are hosting "this" (our) server which is not true. I know you run your own server which may be what you are talking about, but it's very easy to misinterpret that. I've edited your comment so as to not mislead anyone (unless I didn't get a memo sometime).

@Saiyaken-PHOENIX Thank you for the offer, but since the beginning the project has always been free so I don't have any intentions of accepting donations. I don't mind if any of the people who have contributed to the server drop a link to their Paypal or something like that, but the official stance of the project is that we won't accept donations.
