### ISSUE TITLE
Setting up a server in windows

### ISSUE THREAD

**Issue by gokudp** [barronwaffles/dwc_network_server_emulator#321]
how can i do Dnsmasq alternative on windows?
how to get The Twisted framework for Python in windows?

please some instrunctions for windows

**Comment by arves100** [comment]
You can't install Dnsmasq because it's linux only.
But there's a windows alternative called DNSAgent
https://github.com/stackia/DNSAgent/releases/tag/v1.6.5781

For python twisted make sure you have "pip" in your path.
type the following command: pip install twisted

Copy DNSAgent into a folder like Program Files
Install DNSAgent as a Service and run it from services.msc

# 

Open rules.cfg from DNSAgent
Delete everything and paste this:
[
    {
        "Pattern": "^(.*\.)?nintendowifi\.net$",
        "Address": "your ip"
    }
]

After that start DNSAgent
