### ISSUE TITLE
DLC

### ISSUE THREAD

**Issue by SilverSzymonPL** [barronwaffles/dwc_network_server_emulator#346]
In the wiki it says that you need to set the DS date to match the line number of the item you want to get, but how are you supposed to get items with number higher than 365 if a year only has 365 days?

**Comment by AdmiralCurtiss** [comment]
In Gen 5 games it's a bit more complicated than that since each game and game mode only accesses a subset of the files, but all files for all regions are in the same directory. From what I remember, you can probably still find the ID by finding the type/region string of the thing you access (ie, MYSTERY_E for English Mystery Gift), then counting the lines with that string.

Or just go sequential from January 1st until you loop, it's not that many gifts and you probably want most of them anyway.

**Comment by SilverSzymonPL** [comment]
Well that's complicated, but i guess that's an answer

**Comment by SilverSzymonPL** [comment]
But how exactly do i do the 1st method?
