### ISSUE TITLE
authp should not rely on a previous connection to gpcm/profile-server to create an entry in the users table

### ISSUE THREAD

**Issue by SMTDDR** [barronwaffles/dwc_network_server_emulator#41]
Don't know if any WII games are getting connection errors because of this, but...

The official servers can respond to authp without ever seeing a corresponding connection to gpcm profile server or POST /ac acctcreate. 

https://github.com/polaris-/dwc_network_server_emulator/blob/master/gamespy/gs_database.py#L358

First, <code>create_user</code> could be renamed to <code>create_or_update_user</code> and the method <code>generate_authtoken</code> should call <code>create_or_update_user</code> at the end. If the user exist, UPDATE, otherwise INSERT. The only reason I say update is because perhaps weird things happen with dolphin players; in reality a normal WII console should never change any of those values and the UPDATE wouldn't ever contain data different from what's already in the table. Except for the time fields I guess.

**Comment by AdmiralCurtiss** [comment]
This is technically solved but your method is probably a better way to handle it in general.

Also you might want to split that whole "fyi" text block to another issue since it doesn't really have a whole lot to do with this one. (https://github.com/polaris-/dwc_network_server_emulator/commit/982c70eba7a1cf6da76b40ceed3dab1390856944#commitcomment-6673029)
