### ISSUE TITLE
dsi system update?

### ISSUE THREAD

**Issue by Valkristh** [barronwaffles/dwc_network_server_emulator#433]
There is a system update connecting through altwfc dns
(I have 1.4.5U)
Someone know something about that??

**Comment by BevP90** [comment]
I haven't any ideas, my DSI XL is on 1.4.5E and I'm still waiting for my R4i card to get to my door so I can hopefully play some online. In the mean time, I got my broken ds lite online just recently so that was pretty cool. Can't actually play it though because the rubber that makes the contact on the dpad is worn out, so I cannot press left or down. None the less, something to do in the mean time. If Animal Crossing Wild World could be patched, I'd be all over that online aha. I will get into Mortal Kombat 3 soon though.  I'm stuck to playing games that use the touchscreen only.
