### ISSUE TITLE
[REQUEST] WfcPatcher as an IPS/UPS/XDELTA Patch file

### ISSUE THREAD

**Issue by malekairmaroc7** [barronwaffles/dwc_network_server_emulator#494]
Hey there!

Could you do an IPS/UPS or XDELTA Patch for easy patching with WfcPatcher without PC please?

**Comment by fancythedeveloper** [comment]
If you have a xDelta patcher, it should have an option to make a xDelta patch file using a vanilla rom and a modded rom.

**Comment by malekairmaroc7** [comment]
I mean a XDELTA/IPS OR UPS patch of WfcPatcher. Why I need Vanilla ROM and a Modded ROM to do that? Do you mean the Android ROMS? Do ya misunderstood something?

**Comment by fancythedeveloper** [comment]
No, you need the vanilla/unpatched rom, then the modded/patched rom to make a xDelta patch file.
For example: If, for say MKDS. I swapped Mario Curcuit for Blue Loop.
I would need to have the vanilla MKDS rom with Mario Curcuit and the modded rom with Blue Loop in order to make a xDelta patch file.
Pic: 
![image](https://user-images.githubusercontent.com/30706150/43668087-1b8d0f78-9749-11e8-9033-aa28b6534b26.png)

**Comment by malekairmaroc7** [comment]
Aaa. Sorry I misunderstood what you said

**Comment by malekairmaroc7** [comment]
Is it possible to make that on android too?

**Comment by fancythedeveloper** [comment]
Depends on the xDelta patchers that are on Android. Maybe one of them can.

**Comment by malekairmaroc7** [comment]
No one currently can this...
