### ISSUE TITLE
is the server down

### ISSUE THREAD

**Issue by ghost** [barronwaffles/dwc_network_server_emulator#90]
my wii  connection test says its successful but when I try to connect to it with brawl I get error code 20101

**Comment by kyle95wm** [comment]
apparently it is. Use BeanJR-Fi instead for the time being. http://beanjr.hopto.org - do a ping/dig to find the IP address

**Comment by haddy3** [comment]
1. I have tried to connect to the altwfc server during the past 2 days and I am getting the same error code 20101 "The Nintendo Wi-Fi Connection is currently experiencing problems due to a high amount of players, or is temporarily down. Please try again later.". I am not sure what the problem is as the altwfc server was up at the point of attempted connection, and I have also checked for correct DNS settings and SSL patching. Trace analysis through Wireshark also did not reveal any apparent connection problems.
2. Just a side question, I am currently using a fiber optic broadband connection on IPoE and DHCP protocols. Will this affect connection to altwfc in any way? The network setup is as follows:

![fiberopticnet](https://cloud.githubusercontent.com/assets/10266051/5521460/c892f7e8-89db-11e4-95a8-75b8d0b51b99.jpg)
1. @BeanJr, I understand that you have set up your own server recently and is the above post an invitation to public to use BeanJF-Fi (99.238.209.85)? If it is, is there any pre-requisites before we can join your server? (registration, non-emulation etc?) :grin:

**Comment by kyle95wm** [comment]
@haddy3 - Yes you're correct I have set up a server recently, which by the way is getting a ban system from the help of @SMDDR in a few days time.

The only prerequisite right now is to submit your Wii SN to me so i know who you are, because right now its difficult to tell who everyone is in the room just by their PID.

As for the rules, anything is allowed, but if things get too out of hand (trolling, FTW hacking, etc) then I ban the person who committed such an act.

As for Dolphin, I'd like to say Dolphin isn't allowed, but I don't want to be as restrictive as Wiimmfi. The reason I say this is because some people have REALLY good computers that can run Dolphin without a hitch while others have crappy CPU which make Dolphin lag and cause the user to get a higher place than what they really should be getting and could get classified as a FTW hacker because we might think they're using a timer hack. I will of course leave Dolphin use to the user's discretion but if things get too out of hand here, I might start banning Dolphin as well as it could also be used for ban evasion in which case I'll just ban the IP in question.

FYI to anyone - If ALTWFC is down feel free to use my server. Sure you'll have to create a new license, but at least you all have somewhere to go when ALT is down.

**Comment by haddy3** [comment]
@BeanJr, it's really cool that you are able to set up your own server with the help of SMDDR here. But with so many blatant cheaters/hackers in games like Mario Kart it must be a real pain to regulate and give users a good online experience :grimacing: On the other hand, I'm looking for an alternate server for the DS to use GTS so i'll pass i guess. 

Thanks for sharing though! :+1:
