### ISSUE TITLE
Duplicate userid's

### ISSUE THREAD

**Issue by kyle95wm** [barronwaffles/dwc_network_server_emulator#97]
Had no idea where to post this so here I go.

Anyways I brought this issue up in IRC and it still baffles me how these ID's are generated.

This issue is being posted because whenever I send out ban waves to a specific person's "console" tons of other consoles belonging to legit people are also banned (they clearly have different SN's, CFC's, IP, etc

I was playing around with a working theory where if one ID gets banned (assuming this ID is assigned to many consoles - why the hell would it be in the first place is beyond me) and found that I can un-ban selective profiles manually from the database but the only downside is, the console can't create NEW profiles (that is if something goes horribly wrong) so I was wondering, is it possible to create some sort of condition in the ban system where a certain console that is assigned to an userid amung multiple consoles can only create new profiles (this assumes the server is able to check against a valid MAC, SN and CFC)?

This doesn't sound too hard to do imo or maybe it would be I'm not sure

Someone feel free to fill me in on this because right now, banning userid's may APPEAR to be the best option, but then we have the problem with banning people we didn't intentionally want to ban to begin with.

**Comment by SMTDDR** [comment]
@polaris- 
I don't know how MarioKartWii works but I just remembered an umimplemented feature that nas_server never did.  nas_server.py when presented with a POST /ac action=acctcreate is suppose to return a new userid. That's what the official WFC did. Maybe some games just go into some undefined behavior if it doesn't get that value back and perhaps that's how we end up with these alleged userid collisions. This is my python code from years ago that worked against the official server.

```
myheaders = {'User-Agent':'RVL SDK/1.0','HTTP_X_GAMECD':'STKE','Content-Type':'application/x-www-form-urlencoded','Connection':'close','Host':'naswii.nintendowifi.net'}
ac_postdata = "action=YWNjdGNyZWF0ZQ%2A%2A&ingamesn=XXXXXXXXXXXXXXXXXXXXXXXX&sdkver=XXXXXXXX&gamecd=U1RLRQ%2A%2A&makercd=MDg%2A&unitcd=MQ%2A%2A&macadr=MDAxN2FiNDQ3N2M5&lang=MDE%2A&devtime=XXXXXXXXXXXXXXXX&csnum=XXXXXXXXXXXXXXX%2A&cfc=NjIzNjM1OTUzNTYxNTg5MQ%2A%2A"
print "INFO: Connecting to nas.nintendowifi.net..."
conn = httplib.HTTPSConnection("nas.nintendowifi.net")
print "INFO: POST /ac",ac_postdata
conn.request("POST","/ac",ac_postdata,myheaders)
resp = conn.getresponse()
responsedata = resp.read()
print "INFO: NASWII response:",responsedata
userid = re.findall("userid=(.+?)&",responsedata)[0]
print "INFO: userid",base64.urlsafe_b64decode(re.sub("\*","=",userid))
```

I might submit a PR that simply does <code>select max(userid) from users;</code>, increments the value and returns it to the game. Probably for the official servers the userid was an integer column with autoincrement on to prevent any race conditions of the same userid being returned to 2 Wiis who both asked for one at the same time.

@BeanJr 
Can you search your nas_server.log file for the string **YWNjdGNyZWF0ZQ** or **acctcreate**? Or just give me the nas_server.log. If it turns out that the acctcreate command is used for MarioKartWii then I want to fix the problem there first because it may be the reason you see duplicate userids and this fix might make everyone unique and thus a whitelist won't be needed. Otherwise, the whitelist table will probably contain columns userid,gameid,macadr and I can probably make a whitelist management webUI from the users table. I'll get around to it hopefully soon.

**Comment by kyle95wm** [comment]
hey smtddr I got the log from Dec 29th

http://pastebin.com/mJU5pVEH it has the acct create line so go nuts

**Comment by SMTDDR** [comment]
Ok, so per conversation in IRC, apparently MarioKartWii never uses "acctcreate". 

So I'll be adding  a table to gpcm called whitelist that will 3 columns(userid,gameid,macadr) and a webUI that lets you manually enter rows and a button to remove the rows that are already in there.

**Comment by kyle95wm** [comment]
Sorry if this is off topic but this just happened to the admin page. http://prntscr.com/5po3ts

**Comment by SMTDDR** [comment]
@BeanJr 
O_o ....I guess that means there's a game that doesn't have a gsbrcd value.... I'll fix that too.

**Comment by SMTDDR** [comment]
@BeanJr 
Whitelist support - https://github.com/SMTDDR/dwc_network_server_emulator/commit/bb133877d211a5abb916c457462ad986e145a159

Also notice I changed how the admin account info is stored based on suggestion from polaris. You need to create file called adminpageconf.json and put this in it:  

```
   {"username":"admin","password":"opensesame"}
```

But be sure to use a different username and/or password than the example I just pasted.

**Comment by kyle95wm** [comment]
Well I guess we can close this issue for now...

**Comment by kyle95wm** [comment]
Thought I'd reopen this issue as some rather interesting info came my way just now

"The "user ID" is just a decoded variant of the "console nick". The one you wrote probably belongs to dolphin. 

These nicks are generated by Nintendo during the first connection of a Wii (that server is still up). The nick you wrote is the "default" nick which is hard-coded in the system menu until the Wii connects to Nintendo to get a new one. And as Dolphin can't connect to those servers, every Dolphin instance has the user ID 0788854533918. 

The "user ID" in altwfc is similar to the "family ID" on Wiimmfi. " according to Leseratte
